service:
   name: alexa-congregation-count

# Add the serverless-webpack plugin
plugins:
   - serverless-webpack

custom:
   config: ${file(./config/config.js)}
   webpack:
      includeModules:
         forceInclude:
            - tedious


provider:
   name: aws
   runtime: nodejs8.10
   memorySize: 512
   vpc: ${self:custom.config.vpc}
   environment:
      DB_DIALECT: ${self:custom.config.db.dialect}
      DB_HOST: ${self:custom.config.db.host}
      DB_DATABASE: ${self:custom.config.db.database}
      DB_USERNAME: ${self:custom.config.db.credentials.username}
      DB_PASSWORD: ${self:custom.config.db.credentials.password}

functions:
   skillHandler:
      handler: src/handler.handle
      events:
         - alexaSkill: ${self:custom.config.skillID}
      timeout: 60
